### ISSUE TITLE
About data preprocessing

### ISSUE THREAD

**Issue by Mrslock** [rohanchandra30/Spectral-Trajectory-Prediction#11]
hello, thx a lot for sharing your work! When I download the APOLLO dataset from "http://apolloscape.auto/trajectory.html", I unzip them and run "format_apolloscape.py",
but it needs to acess "/sample_trajectoryasdt_sample_ trajectory/APOL/train/" while I can not find this directory in my unzipped file, did I download the wrong version of this dataset?

**Comment by srujanpanuganti** [comment]
Hi Mrslock,

The format_apolloscape.py looks for "/sample_trajectory/asdt_sample_ trajectory/APOL/train/" to save the formatted files. You can manually create empty folders in that format. 

Create a folder with name "APOL" and three more folders named "train", "val", "test"  inside "APOL".
Follow the same procedure to create LYFT and ARGO folders if you face similar problem with those datasets.

Let me know if this solves your problem.

Regards,
Srujan

**Comment by Mrslock** [comment]
Thanks a lot for your quick reply, So I also need to create "resources" folder and run some  functions in data_preprocessing to generate input for main function, is that correct?

**Comment by Mrslock** [comment]
I suppose if I run "setup.py" successfully, then I need not to do the "Data preparation steps" in README.md, but when I run "setup.py", I encountered the problem:
 File "/DB/rhome/yfhu/anaconda3/envs/sc-glstm/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='docs.google.com', port=443): Max retries exceeded with url: /uc?export=download&id=1QT7iKrcYLqV9PghURj0zmHs7KXs-0F16 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fe3ad260910>: Failed to establish a new connection: [Errno 110] Connection timed out'))
is it caused by network issue?

**Comment by srujanpanuganti** [comment]
Yes setup.py will create the whole directory sturcture that's necessary. The error you're mentioning is a network issue.

**Comment by Mrslock** [comment]
it seems difficult for me to download resources folder by running "setup.py", it there an other access?

**Comment by rayguan97** [comment]
You can access it through this link. https://drive.google.com/file/d/1QT7iKrcYLqV9PghURj0zmHs7KXs-0F16/view

**Comment by rohanchandra30** [comment]
Although setup.py should automatically download resources, isn't that so @rayguan97  ?

**Comment by rayguan97** [comment]
Yes, running setup.py will work. 

But if you still can't download it from the browser, then you can try a different internet connection.

**Comment by Mrslock** [comment]
Thanks a lot

**Comment by rohanchandra30** [comment]
Closing this out - let us know if you have further questions !

**Comment by leeinscky** [comment]
It solved my problem, thanks so much!
