### ISSUE TITLE
The coordinate system of the lyft dataset?

### ISSUE THREAD

**Issue by SpyderXu** [rohanchandra30/Spectral-Trajectory-Prediction#3]
It seems that you extract the tracking trajectory of the lyft dataset, so the coordinate system of the lyft dataset is the world coordinate or the camera (or lidar) coordinate?

**Comment by rohanchandra30** [comment]
It's the world coordinate. They have data of 6 cameras and 4 lidars, the final location data is a consolidated data after analyzing all these cameras data and lidar data.

**Comment by rohanchandra30** [comment]
Closing this out now. Feel free to reopen in case of any further questions.
