### ISSUE TITLE
Data stream is not runnable

### ISSUE THREAD

**Issue by ycj2014** [rohanchandra30/Spectral-Trajectory-Prediction#9]
Hi,
I was trying to process Apolloscape dataset with the processing scripts given. However, there are some points quite confusing to me. 

1. Delete y position of the agent as shown in [here](https://github.com/rohanchandra30/Spectral-Trajectory-Prediction/blob/8a22e7e2e5d0834925f761ff58642454caa18e6c/data_processing/format_apolloscape.py#L161) .But the 4th position in the line is position_y.

2. The code seems try to load a directory as a txt file as shown in [here](https://github.com/rohanchandra30/Spectral-Trajectory-Prediction/blob/8a22e7e2e5d0834925f761ff58642454caa18e6c/data_processing/data_stream.py#L29)

Thank you!
TN

**Comment by srujanpanuganti** [comment]
> Hi,
> I was trying to process Apolloscape dataset with the processing scripts given. However, there are some points quite confusing to me.
> 
>     1. Delete y position of the agent as shown in [here](https://github.com/rohanchandra30/Spectral-Trajectory-Prediction/blob/8a22e7e2e5d0834925f761ff58642454caa18e6c/data_processing/format_apolloscape.py#L161) .But the 4th position in the line is position_y.
> TN

Hi,
Replying to your first doubt, [this line](https://github.com/rohanchandra30/Spectral-Trajectory-Prediction/blob/8a22e7e2e5d0834925f761ff58642454caa18e6c/data_processing/format_apolloscape.py#L161) will delete the Rows 5,6,7,8,9 from the obtained array. The line doesn't delete position_y.

Thank you,
Srujan

**Comment by srujanpanuganti** [comment]
> Hi,
> I was trying to process Apolloscape dataset with the processing scripts given. However, there are some points quite confusing to me.
>     2. The code seems try to load a directory as a txt file as shown in [here](https://github.com/rohanchandra30/Spectral-Trajectory-Prediction/blob/8a22e7e2e5d0834925f761ff58642454caa18e6c/data_processing/data_stream.py#L29)
> 
> 
> Thank you!
> TN

Replying to you second query, I have now added additional comments on how the dir has to be provided to the function data_for_stream1 and data_for_stream2.

Please let me know if you have any further queries

Thank You 
Srujan

**Comment by rohanchandra30** [comment]
Let us know if there are further questions.
